#asset("assets/site.css", read("/src/assets/site.css"))
#asset("assets/site.js", read("/src/assets/site.js"))
#asset("assets/search.css", read("/src/assets/search.css"))
#asset("assets/search.js", read("/src/assets/search.js"))
#asset("assets/fonts/NotoSans-VariableFont_wdth,wght.ttf", read("/src/assets/fonts/NotoSans-VariableFont_wdth,wght.ttf", encoding: none))
#asset("assets/fonts/NotoSansMath-Regular.otf", read("/src/assets/fonts/NotoSansMath-Regular.otf", encoding: none))
#asset("assets/fonts/FiraMath-Regular.otf", read("/src/assets/fonts/FiraMath-Regular.otf", encoding: none))
#asset("assets/fonts/NewCMMath-Book.otf", read("/src/assets/fonts/NewCMMath-Book.otf", encoding: none))
#asset("assets/github.svg", read("/src/assets/github.svg"))
#asset("assets/search.svg", read("/src/assets/search.svg"))
#asset("assets/print.svg", read("/src/assets/print.svg"))
#asset("assets/download.svg", read("/src/assets/download.svg"))
#asset("assets/eye.svg", read("/src/assets/eye.svg"))
#asset("assets/sun.svg", read("/src/assets/sun.svg"))
#asset("assets/moon.svg", read("/src/assets/moon.svg"))
#asset("assets/theme.svg", read("/src/assets/theme.svg"))
#asset("assets/menu.svg", read("/src/assets/menu.svg"))
#asset("assets/toc.svg", read("/src/assets/toc.svg"))
