name: Build and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: |
          pip install numpy shapely beautifulsoup4

      # - name: Run preprocessing script
      #   run: python scripts/build.py

      # A custom typst executable is necessary for compilation due to additional modifications required
      - name: Build Document
        run: |
          Remove-Item -Recurse -Force web/dist -ErrorAction SilentlyContinue
          Remove-Item -Recurse -Force dist -ErrorAction SilentlyContinue
          .\typst.exe compile --features bundle,html --format bundle --package-path packages main.typ dist

      - name: Build Search Index
        run: python build-search-index.py

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
